## Global Variables
@baseurl=http://127.0.0.1:5000

### 1. Login Admin
# @name Login
POST {{baseurl}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Simpan token dari response di atas untuk digunakan di bawah
@authToken = {{Login.response.body.access_token}}


---

## Generate Food Data
# @name PostGenerateFood
POST {{baseurl}}/foods/generate
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "theme": "Masakan Tradisional Batak",
  "total": 3
}

### Response Expected:
# {
#   "data": ["Arsik Ikan Mas", "Saksang", "Manuk Napinadar"],
#   "theme": "Masakan Tradisional Batak",
#   "total": 3
# }


---

## Get All Food Data
# @name GetFoods
GET {{baseurl}}/foods?page=1&per_page=10
Content-Type: application/json
###

---

## Logout (Local)
# @name Logout
POST {{baseurl}}/auth/logout
Authorization: Bearer {{authToken}}
###